feat: implement last 4 steps of apple attestation
bcgov/mobile-attestation-vc-controller pull request #11
Opened 2023-11-30 04:22 UTC by bryce-mcmath

Pushing this PR so @jleach can try it out and give feedback before we continue with moving the relevant code from `apple.py main()` to `verify_attestation_statement()` and add caching for end to end functionality

2023-11-30 20:04 UTC, jleach requested changes

2023-11-30 20:04 UTC, jleach commented on src/apple.py
> +    counter_start = 33
constants.ts?

2023-12-01 02:34 UTC, bryce-mcmath commented on src/apple.py
> +    cred_id_start = 55
done

2023-12-01 02:34 UTC, bryce-mcmath commented on src/apple.py
> +    counter_start = 33
done

2023-12-01 02:34 UTC, bryce-mcmath commented on src/apple.py
> +    app_id = 'L796QSLV3E.ca.bc.gov.BCWallet'
done

2023-12-01 15:24 UTC, jleach requested changes

2023-12-01 15:24 UTC, jleach commented on src/apple.py
> +    app_id = 'L796QSLV3E.ca.bc.gov.BCWallet'
To constants.py?

2023-12-04 20:45 UTC, bryce-mcmath commented on src/apple.py
> +    app_id = 'L796QSLV3E.ca.bc.gov.BCWallet'
done

2023-12-05 23:55 UTC, jleach approved these changes

2023-12-05 23:56 UTC, merged