fix: add more logs and fetch fresh google creds each attestation
bcgov/mobile-attestation-vc-controller pull request #40
Opened 2024-04-02 23:14 UTC by bryce-mcmath

Adding more logs and moving the google credentials from global scope to function scope, fetched every time so they don't expire over time. I'm hoping that's what was causing the problems after a day or so.

2024-04-02 23:18 UTC, jleach requested changes

2024-04-02 23:18 UTC, jleach commented on src/goog.py
> +            path, scopes=["https://www.googleapis.com/auth/playintegrity"]
constants.py?

2024-04-02 23:18 UTC, jleach commented on src/traction.py
> +        logger.info(f"Text content for error: {response.text}")
Do we have "logger.error"?

2024-04-03 00:02 UTC, bryce-mcmath commented on src/goog.py
> +            path, scopes=["https://www.googleapis.com/auth/playintegrity"]
Done

2024-04-03 00:02 UTC, bryce-mcmath commented on src/traction.py
> +        logger.info(f"Text content for error: {response.text}")
Yes, done

2024-04-03 16:16 UTC, jleach approved these changes

2024-04-03 16:42 UTC, merged