feat: working version of android attestation poc
bcgov/mobile-attestation-vc-controller pull request #5
Opened 2023-10-30 18:58 UTC by bryce-mcmath

Tried to keep it simple. There are couple things we can do to increase the assurance. 
1) Cache our nonce's with their associated connection id and verify that the original nonce matches the nonce returned with the integrity verdict (see the sample verdict JSON)
2) Include the check for the `appRecognitionVerdict` being `PLAY_RECOGNIZED` but that breaks testing it in development

2023-11-03 16:01 UTC, jleach requested changes

2023-11-03 16:01 UTC, jleach commented on src/__pycache__/apple.cpython-311.pyc
Can we remove?

2023-11-03 16:01 UTC, jleach commented on src/__pycache__/traction.cpython-311.pyc
Can we remove?

2023-11-03 16:04 UTC, jleach requested changes

2023-11-03 16:04 UTC, jleach commented on src/goog.py
> +    # tokenStr = "eyJhbGciOiJBMjU2S1ciLCJlbmMiOiJBMjU2R0NNIn0.KFblol_9JhOlET2f9elkRQikcIT9es3um64ZnvuAREYfJNvWYVlkVA.cxjbb-d8n6JBCCE5.9OXiSYrz7_PIRGGzwUMO0M_Fp66gPwYphTsJwY1eF-vYnKGTnHtxxIIuriNAHBxPB
Can we remove the comment?

2023-11-05 00:38 UTC, bryce-mcmath commented on src/__pycache__/apple.cpython-311.pyc
this file is being deleted

2023-11-05 00:38 UTC, bryce-mcmath commented on src/__pycache__/traction.cpython-311.pyc
same as above

2023-11-05 00:38 UTC, bryce-mcmath commented on src/goog.py
> +    # tokenStr = "eyJhbGciOiJBMjU2S1ciLCJlbmMiOiJBMjU2R0NNIn0.KFblol_9JhOlET2f9elkRQikcIT9es3um64ZnvuAREYfJNvWYVlkVA.cxjbb-d8n6JBCCE5.9OXiSYrz7_PIRGGzwUMO0M_Fp66gPwYphTsJwY1eF-vYnKGTnHtxxIIuriNAHBxPB
will do

2023-11-06 22:08 UTC, merged